version: '3.9'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch.yml
        target: /usr/share/elasticsearch.yml
        read_only: true
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9201
      - 9301:9300
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    environment:
      SERVER_NAME: kibana.KingCode.org
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5600:5601
    networks:
      - elk

volumes:
  esdata:

networks:
  elk:
    driver: bridge